import type { ComponentType } from 'react';

export interface DocFrontmatter {
  title?: string;
  sidebar_position?: number;
  description?: string;
}

interface DocModule {
  default: ComponentType;
  frontmatter?: DocFrontmatter;
}

export interface DocPage {
  slug: string; // e.g. "deep-learning/attention-demo"
  route: string; // e.g. "/docs/deep-learning/attention-demo"
  title: string;
  sidebarPosition: number;
  section: string; // top-level folder name, e.g. "deep-learning"
  Component: ComponentType;
}

export interface SidebarSection {
  id: string;
  label: string;
  pages: DocPage[];
}

function titleCase(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/**
 * Scans every .mdx file under src/content/docs at module-load time (Vite's
 * import.meta.glob, eager so this resolves synchronously) and builds a
 * route list + grouped sidebar tree from it -- the Vite-native replacement
 * for sidebars.js's {type:'autogenerated', dirName} pattern: group = the
 * page's immediate parent folder, order within a group = frontmatter's
 * sidebar_position, page title = frontmatter.title (falling back to a
 * title-cased filename so an un-annotated page still renders sensibly).
 */
const modules = import.meta.glob<DocModule>('/src/content/docs/**/*.mdx', { eager: true });

function buildPages(): DocPage[] {
  const pages: DocPage[] = [];
  for (const [path, mod] of Object.entries(modules)) {
    const rel = path.replace('/src/content/docs/', '').replace(/\.mdx$/, '');
    const parts = rel.split('/');
    const section = parts.length > 1 ? parts[0] : 'general';
    const fm = mod.frontmatter ?? {};
    pages.push({
      slug: rel,
      route: `/docs/${rel}`,
      title: fm.title ?? titleCase(parts[parts.length - 1]),
      sidebarPosition: fm.sidebar_position ?? 999,
      section,
      Component: mod.default,
    });
  }
  return pages;
}

const allPages = buildPages();

export function getSidebar(): SidebarSection[] {
  const bySection = new Map<string, DocPage[]>();
  for (const page of allPages) {
    const list = bySection.get(page.section) ?? [];
    list.push(page);
    bySection.set(page.section, list);
  }
  const sections: SidebarSection[] = [];
  for (const [id, pages] of bySection) {
    pages.sort((a, b) => a.sidebarPosition - b.sidebarPosition || a.title.localeCompare(b.title));
    sections.push({ id, label: titleCase(id), pages });
  }
  sections.sort((a, b) => a.label.localeCompare(b.label));
  return sections;
}

/** Flattened, sidebar-ordered page list -- drives prev/next navigation. */
export function getFlatPages(): DocPage[] {
  const sections = getSidebar();
  return sections.flatMap((s) => s.pages);
}

export function getPageByRoute(route: string): DocPage | undefined {
  return allPages.find((p) => p.route === route);
}

export function getPrevNext(route: string): { prev?: DocPage; next?: DocPage } {
  const flat = getFlatPages();
  const idx = flat.findIndex((p) => p.route === route);
  if (idx === -1) return {};
  return { prev: flat[idx - 1], next: flat[idx + 1] };
}
