import { lazy, type ComponentType } from 'react';
import pageMeta from '../data/pageMeta.generated.json';
import lastUpdatedMap from '../data/lastUpdated.generated.json';

export interface DocFrontmatter {
  title?: string;
  sidebar_position?: number;
  description?: string;
  /** Practice-problem-only fields (Phase 2 of the Learn/Practice split) --
   * absent on every other page. */
  difficulty?: 'easy' | 'medium' | 'hard';
  topic?: string;
}

/** Real, top-level "difficulty" spelling for a practice problem -- 'easy' |
 * 'medium' | 'hard', absent on the 4 system-design challenges (a
 * free-text+rubric problem shape difficulty doesn't cleanly apply to). */
export type PracticeDifficulty = 'easy' | 'medium' | 'hard';

interface DocModule {
  default: ComponentType;
  frontmatter?: DocFrontmatter;
}

export interface DocPage {
  slug: string; // e.g. "deep-learning/attention-demo"
  /** The page's real, canonical URL. For every page EXCEPT a practice
   * problem this is "/docs/<slug>" (unchanged). Practice-problem pages are
   * remapped to "/practice/<slug-without-the-practice-problems-prefix>" --
   * they're a real top-level destination now (see PracticeListPage), not a
   * docs subsection, and old /docs/practice-problems/* links redirect here
   * (see App.tsx) rather than the file's content or location moving. */
  route: string;
  title: string;
  description?: string;
  sidebarPosition: number;
  section: string; // top-level folder name, e.g. "deep-learning"
  Component: ComponentType;
  lastUpdated?: string; // ISO date of the most recent commit touching this page, from lastUpdated.generated.json
  /** Practice-problem-only fields, undefined on every other page. */
  difficulty?: PracticeDifficulty;
  topic?: string;
}

export interface SidebarSection {
  id: string;
  label: string;
  position: number;
  pages: DocPage[];
}

function titleCase(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/**
 * Builds the route list + grouped sidebar tree from pageMeta.generated.json
 * (see scripts/generate-page-meta.mjs) -- plain static data, not an eager
 * import.meta.glob over every .mdx file. The Vite-native replacement for
 * sidebars.js's {type:'autogenerated', dirName} pattern: group = the page's
 * immediate parent folder, order within a group = frontmatter's
 * sidebar_position, page title = frontmatter.title (falling back to a
 * title-cased filename so an un-annotated page still renders sensibly).
 *
 * Each section folder's _category_.json (migrated verbatim from Docusaurus,
 * same {label, position} shape) drives the section's sidebar label and
 * ordering -- titleCase(folderName) alone gets slugs like "cs-fundamentals"
 * or "llms-genai" wrong ("Cs Fundamentals", "Llms Genai" instead of "CS
 * Fundamentals for AI Engineers", "LLMs & GenAI"). Falls back to
 * titleCase + alphabetical for any section that doesn't have one.
 *
 * The actual page COMPONENT is loaded lazily (React.lazy over a non-eager
 * import.meta.glob) -- deliberately decoupled from the metadata above.
 * Previously this glob was `{ eager: true }`, which meant every page's
 * compiled component (and every diagram it imports) was bundled into and
 * downloaded as part of the single entry chunk on every route, regardless
 * of which page was actually requested -- confirmed via a real Fast-3G
 * Playwright load test to cost ~28s to `load` on every route before this
 * split. DocLayout.tsx wraps rendering in <Suspense> to match.
 */
const componentLoaders = import.meta.glob<DocModule>('/src/content/docs/**/*.mdx');

interface PageMetaEntry {
  slug: string;
  section: string;
  title: string | null;
  sidebarPosition: number | null;
  description: string | null;
  difficulty: PracticeDifficulty | null;
  topic: string | null;
}

const PRACTICE_PROBLEMS_SECTION = 'practice-problems';
const PRACTICE_PROBLEMS_PREFIX = `${PRACTICE_PROBLEMS_SECTION}/`;
interface CategoryMetaEntry {
  label: string;
  position?: number;
}
const typedPageMeta = pageMeta as { pages: Record<string, PageMetaEntry>; categories: Record<string, CategoryMetaEntry> };

/** A practice problem's real, top-level "/practice/<slug>" URL -- the
 * file's own content/location never moves, only the URL it's reachable
 * at. "overview" has no practice-problem equivalent (superseded by the
 * real PracticeListPage at /practice itself), so it's excluded from
 * allPages entirely rather than given a route -- see App.tsx for the
 * redirect that sends its old URL to /practice. */
function practiceRoute(slug: string): string | null {
  const name = slug.slice(PRACTICE_PROBLEMS_PREFIX.length);
  return name === 'overview' ? null : `/practice/${name}`;
}

function buildPages(): DocPage[] {
  const pages: DocPage[] = [];
  for (const [docsRoute, meta] of Object.entries(typedPageMeta.pages)) {
    const modulePath = `/src/content/docs/${meta.slug}.mdx`;
    const loader = componentLoaders[modulePath];
    if (!loader) {
      // pageMeta.generated.json is stale relative to the actual file tree
      // (e.g. a file was renamed/deleted without rerunning `predev`/`prebuild`
      // -- see scripts/generate-page-meta.mjs) -- fail loudly at startup
      // rather than a page silently 404ing on click.
      throw new Error(`contentTree: no component module found for ${modulePath} -- try re-running \`node scripts/generate-page-meta.mjs\``);
    }

    let route = docsRoute;
    if (meta.section === PRACTICE_PROBLEMS_SECTION) {
      const remapped = practiceRoute(meta.slug);
      if (!remapped) continue; // overview.mdx -- see practiceRoute's comment
      route = remapped;
    }

    pages.push({
      slug: meta.slug,
      route,
      title: meta.title ?? titleCase(meta.slug.split('/').pop()!),
      description: meta.description ?? undefined,
      sidebarPosition: meta.sidebarPosition ?? 999,
      section: meta.section,
      lastUpdated: (lastUpdatedMap as Record<string, string>)[docsRoute],
      Component: lazy(() => loader() as Promise<{ default: ComponentType }>),
      difficulty: meta.difficulty ?? undefined,
      topic: meta.topic ?? undefined,
    });
  }
  return pages;
}

const allPages = buildPages();

/** Every real practice-problem page (excluding overview), independent of
 * getSidebar() -- Practice is a separate top-level destination now, not a
 * docs sidebar section (see getSidebar()'s own exclusion below), so
 * PracticeListPage and Home's "N+ problems" count read from here instead. */
export function getPracticeProblems(): DocPage[] {
  return allPages.filter((p) => p.section === PRACTICE_PROBLEMS_SECTION).sort((a, b) => a.sidebarPosition - b.sidebarPosition);
}

export function getSidebar(): SidebarSection[] {
  const bySection = new Map<string, DocPage[]>();
  for (const page of allPages) {
    // Practice problems live at /practice now, not under /docs -- they no
    // longer belong in the Learn docs sidebar (see getPracticeProblems()
    // for where they're read from instead). sectionMeta.ts still lists
    // 'practice-problems' as a real subsection (so topicBreakdown can keep
    // bucketing practice-problem points into a real group) -- see the
    // matching exception in sectionMeta.test.ts.
    if (page.section === PRACTICE_PROBLEMS_SECTION) continue;
    const list = bySection.get(page.section) ?? [];
    list.push(page);
    bySection.set(page.section, list);
  }
  const sections: SidebarSection[] = [];
  for (const [id, pages] of bySection) {
    pages.sort((a, b) => a.sidebarPosition - b.sidebarPosition || a.title.localeCompare(b.title));
    const meta = typedPageMeta.categories[id];
    sections.push({
      id,
      label: meta?.label ?? titleCase(id),
      position: meta?.position ?? 999,
      pages,
    });
  }
  sections.sort((a, b) => a.position - b.position || a.label.localeCompare(b.label));
  return sections;
}

/** Flattened, sidebar-ordered page list -- drives prev/next navigation. */
export function getFlatPages(): DocPage[] {
  const sections = getSidebar();
  return sections.flatMap((s) => s.pages);
}

// GitHub Pages 301-redirects a bare directory path ("/docs/foo") to its
// trailing-slash form ("/docs/foo/") when a matching directory/index.html
// exists there (confirmed against production) -- which the static
// prerendering in scripts/prerender-for-pagefind.mjs now produces for
// every route. Stored routes never carry a trailing slash, so any code
// reading `location.pathname` directly (not just route matching -- also
// e.g. ProgressContext's permalink keys) needs this same normalization,
// or the exact same logical page ends up tracked under two different
// keys depending on whether a visitor arrived via a direct/bookmarked
// URL (redirected, trailing slash) or an in-app <Link> click (not
// redirected, no trailing slash).
export function normalizeRoute(route: string): string {
  return route.length > 1 && route.endsWith('/') ? route.slice(0, -1) : route;
}

export function getPageByRoute(route: string): DocPage | undefined {
  const normalized = normalizeRoute(route);
  return allPages.find((p) => p.route === normalized);
}

export function getPrevNext(route: string): { prev?: DocPage; next?: DocPage } {
  const flat = getFlatPages();
  const idx = flat.findIndex((p) => p.route === route);
  if (idx === -1) return {};
  return { prev: flat[idx - 1], next: flat[idx + 1] };
}
