import { lazy, type ComponentType } from 'react';
import pageMeta from '../data/pageMeta.generated.json';
import lastUpdatedMap from '../data/lastUpdated.generated.json';

export interface DocFrontmatter {
  title?: string;
  sidebar_position?: number;
  description?: string;
}

interface DocModule {
  default: ComponentType;
  frontmatter?: DocFrontmatter;
}

export interface DocPage {
  slug: string; // e.g. "deep-learning/attention-demo"
  route: string; // e.g. "/docs/deep-learning/attention-demo"
  title: string;
  description?: string;
  sidebarPosition: number;
  section: string; // top-level folder name, e.g. "deep-learning"
  Component: ComponentType;
  lastUpdated?: string; // ISO date of the most recent commit touching this page, from lastUpdated.generated.json
}

export interface SidebarSection {
  id: string;
  label: string;
  position: number;
  pages: DocPage[];
}

function titleCase(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/**
 * Builds the route list + grouped sidebar tree from pageMeta.generated.json
 * (see scripts/generate-page-meta.mjs) -- plain static data, not an eager
 * import.meta.glob over every .mdx file. The Vite-native replacement for
 * sidebars.js's {type:'autogenerated', dirName} pattern: group = the page's
 * immediate parent folder, order within a group = frontmatter's
 * sidebar_position, page title = frontmatter.title (falling back to a
 * title-cased filename so an un-annotated page still renders sensibly).
 *
 * Each section folder's _category_.json (migrated verbatim from Docusaurus,
 * same {label, position} shape) drives the section's sidebar label and
 * ordering -- titleCase(folderName) alone gets slugs like "cs-fundamentals"
 * or "llms-genai" wrong ("Cs Fundamentals", "Llms Genai" instead of "CS
 * Fundamentals for AI Engineers", "LLMs & GenAI"). Falls back to
 * titleCase + alphabetical for any section that doesn't have one.
 *
 * The actual page COMPONENT is loaded lazily (React.lazy over a non-eager
 * import.meta.glob) -- deliberately decoupled from the metadata above.
 * Previously this glob was `{ eager: true }`, which meant every page's
 * compiled component (and every diagram it imports) was bundled into and
 * downloaded as part of the single entry chunk on every route, regardless
 * of which page was actually requested -- confirmed via a real Fast-3G
 * Playwright load test to cost ~28s to `load` on every route before this
 * split. DocLayout.tsx wraps rendering in <Suspense> to match.
 */
const componentLoaders = import.meta.glob<DocModule>('/src/content/docs/**/*.mdx');

interface PageMetaEntry {
  slug: string;
  section: string;
  title: string | null;
  sidebarPosition: number | null;
  description: string | null;
}
interface CategoryMetaEntry {
  label: string;
  position?: number;
}
const typedPageMeta = pageMeta as { pages: Record<string, PageMetaEntry>; categories: Record<string, CategoryMetaEntry> };

function buildPages(): DocPage[] {
  const pages: DocPage[] = [];
  for (const [route, meta] of Object.entries(typedPageMeta.pages)) {
    const modulePath = `/src/content/docs/${meta.slug}.mdx`;
    const loader = componentLoaders[modulePath];
    if (!loader) {
      // pageMeta.generated.json is stale relative to the actual file tree
      // (e.g. a file was renamed/deleted without rerunning `predev`/`prebuild`
      // -- see scripts/generate-page-meta.mjs) -- fail loudly at startup
      // rather than a page silently 404ing on click.
      throw new Error(`contentTree: no component module found for ${modulePath} -- try re-running \`node scripts/generate-page-meta.mjs\``);
    }
    pages.push({
      slug: meta.slug,
      route,
      title: meta.title ?? titleCase(meta.slug.split('/').pop()!),
      description: meta.description ?? undefined,
      sidebarPosition: meta.sidebarPosition ?? 999,
      section: meta.section,
      lastUpdated: (lastUpdatedMap as Record<string, string>)[route],
      Component: lazy(() => loader() as Promise<{ default: ComponentType }>),
    });
  }
  return pages;
}

const allPages = buildPages();

export function getSidebar(): SidebarSection[] {
  const bySection = new Map<string, DocPage[]>();
  for (const page of allPages) {
    const list = bySection.get(page.section) ?? [];
    list.push(page);
    bySection.set(page.section, list);
  }
  const sections: SidebarSection[] = [];
  for (const [id, pages] of bySection) {
    pages.sort((a, b) => a.sidebarPosition - b.sidebarPosition || a.title.localeCompare(b.title));
    const meta = typedPageMeta.categories[id];
    sections.push({
      id,
      label: meta?.label ?? titleCase(id),
      position: meta?.position ?? 999,
      pages,
    });
  }
  sections.sort((a, b) => a.position - b.position || a.label.localeCompare(b.label));
  return sections;
}

/** Flattened, sidebar-ordered page list -- drives prev/next navigation. */
export function getFlatPages(): DocPage[] {
  const sections = getSidebar();
  return sections.flatMap((s) => s.pages);
}

export function getPageByRoute(route: string): DocPage | undefined {
  return allPages.find((p) => p.route === route);
}

export function getPrevNext(route: string): { prev?: DocPage; next?: DocPage } {
  const flat = getFlatPages();
  const idx = flat.findIndex((p) => p.route === route);
  if (idx === -1) return {};
  return { prev: flat[idx - 1], next: flat[idx + 1] };
}
