import { useMemo } from 'react';
import { useVizTokens } from '../../theme/vizTokens';
import { VisualizationContainer } from '../primitives';
import { DIAGRAM_TYPE, getConceptColor, valueColor } from './diagramSystem';

const SR = 64; // samples/sec, arbitrary demo units
const DURATION = 3;
const N_TOTAL = SR * DURATION;
const WINDOW = 32;
const HOP = 8;
const FREQ_BINS = WINDOW / 2;

/** Two steady tones, then a rising chirp -- generated by phase accumulation
 * so the chirp's instantaneous frequency sweep is exact, not approximated
 * by a closed-form formula. */
function instantaneousFreq(n: number): number {
  const tt = n / SR;
  if (tt < 1) return 8;
  if (tt < 2) return 14;
  const frac = tt - 2;
  return 4 + (20 - 4) * frac; // chirp: 4Hz -> 20Hz over the last second
}

function generateSignal(): number[] {
  const x: number[] = [];
  let phase = 0;
  for (let n = 0; n < N_TOTAL; n++) {
    phase += (2 * Math.PI * instantaneousFreq(n)) / SR;
    x.push(Math.sin(phase));
  }
  return x;
}

function hann(n: number, N: number): number {
  return 0.5 * (1 - Math.cos((2 * Math.PI * n) / (N - 1)));
}

/** Naive DFT magnitude per STFT frame -- O(window^2) per frame, trivial at
 * this size (32 samples), computed live rather than baked into a static
 * image. */
function computeSpectrogram(x: number[]): number[][] {
  const frames: number[][] = [];
  for (let start = 0; start + WINDOW <= x.length; start += HOP) {
    const mags: number[] = [];
    for (let k = 0; k < FREQ_BINS; k++) {
      let re = 0;
      let im = 0;
      for (let n = 0; n < WINDOW; n++) {
        const sample = x[start + n] * hann(n, WINDOW);
        const angle = (2 * Math.PI * k * n) / WINDOW;
        re += sample * Math.cos(angle);
        im -= sample * Math.sin(angle);
      }
      mags.push(Math.sqrt(re * re + im * im));
    }
    frames.push(mags);
  }
  return frames;
}

const WIDTH = 600;
const WAVE_H = 90;
const SPEC_H = 160;
const PAD_L = 40;
const PAD_R = 10;

export default function WaveformSpectrogramDiagram() {
  const t = useVizTokens();

  const { signal, frames, maxMag } = useMemo(() => {
    const signal = generateSignal();
    const frames = computeSpectrogram(signal);
    const maxMag = Math.max(...frames.flat());
    return { signal, frames, maxMag };
  }, []);

  const plotW = WIDTH - PAD_L - PAD_R;
  const waveColor = getConceptColor(t, 'token');

  const wavePath = signal
    .map((v, i) => {
      const x = PAD_L + (i / (signal.length - 1)) * plotW;
      const y = WAVE_H / 2 - v * (WAVE_H / 2 - 8);
      return `${i === 0 ? 'M' : 'L'} ${x},${y}`;
    })
    .join(' ');

  const cellW = plotW / frames.length;
  const cellH = SPEC_H / FREQ_BINS;

  return (
    <VisualizationContainer footer="Two steady tones are invisible as distinct things in the raw waveform (top -- just a busy oscillating line) but appear as two clean, constant horizontal bands in the spectrogram (bottom). The rising diagonal band is the chirp: a linearly increasing frequency, unreadable in the waveform but immediately obvious once you're looking at the frequency domain. Every cell below is a real magnitude computed by a short-time DFT over that time window -- this is what an STFT actually produces, not an illustration of one.">
      <div style={{ fontSize: DIAGRAM_TYPE.secondaryLabel.size, color: t.textMuted, marginBottom: 2 }}>Waveform (time domain)</div>
      <svg width="100%" viewBox={`0 0 ${WIDTH} ${WAVE_H}`} style={{ display: 'block' }}>
        <line x1={PAD_L} y1={WAVE_H / 2} x2={WIDTH - PAD_R} y2={WAVE_H / 2} stroke={t.border} strokeWidth={1} />
        <path d={wavePath} fill="none" stroke={waveColor} strokeWidth={1} />
      </svg>

      <div style={{ fontSize: DIAGRAM_TYPE.secondaryLabel.size, color: t.textMuted, marginTop: 10, marginBottom: 2 }}>Spectrogram (frequency domain, via STFT)</div>
      <svg width="100%" viewBox={`0 0 ${WIDTH} ${SPEC_H}`} style={{ display: 'block' }}>
        {frames.map((mags, fi) =>
          mags.map((mag, bin) => {
            const x = PAD_L + fi * cellW;
            const y = SPEC_H - (bin + 1) * cellH;
            return <rect key={`${fi}-${bin}`} x={x} y={y} width={cellW + 0.5} height={cellH + 0.5} fill={valueColor(t, 'attention', mag / maxMag)} />;
          }),
        )}
        <text x={PAD_L - 6} y={12} textAnchor="end" fontSize={9} fill={t.textMuted}>high Hz</text>
        <text x={PAD_L - 6} y={SPEC_H - 2} textAnchor="end" fontSize={9} fill={t.textMuted}>0 Hz</text>
      </svg>
      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: DIAGRAM_TYPE.secondaryLabel.size, color: t.textMuted, marginTop: 2, maxWidth: WIDTH }}>
        <span>t = 0s (tone 1)</span>
        <span>t = 1s (tone 2)</span>
        <span>t = 2s (chirp)</span>
        <span>t = 3s</span>
      </div>
    </VisualizationContainer>
  );
}
